name: Add cross-account permissions to an image on ECR
description: Add cross-account permissions to an image on ECR
inputs:
  role-to-assume:
    description: The ARN of the role to assume
    required: true
  policy-json:
    description: The path to the policy JSON you wish to apply
    required: false
runs:
  using: composite
  steps:
    - name: Check out current repository
      uses: actions/checkout@v2
    - name: Check out cross-account repository
      uses: actions/checkout@v2
      with:
        repository: "moj-analytical-services/actions-cross-account-ecr"
        ref: main
        path: "actions-cross-account-ecr"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 3600
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Check ECR Repository Exists
      env:
        ECR_REPOSITORY: ${{ github.event.repository.name }}
      shell: bash
      run: |
        aws ecr describe-repositories --repository-names ${ECR_REPOSITORY,,}
    - name: Check ECR Repository Exists
      env:
        POLICY_JSON: ${{ inputs.policy-json }}
      shell: bash
      run: |
        python ./actions-cross-account-ecr/generate_policy.py
    - name: Add permissions to repository
      env:
        ECR_REPOSITORY: ${{ github.event.repository.name }}
      shell: bash
      run: |
        aws ecr set-repository-policy --repository-name ${ECR_REPOSITORY,,} --policy-text file://./actions-cross-account-ecr/final_policy.json
