name: Add cross-account permissions to an image on ECR
description: Add cross-account permissions to an image on ECR
inputs:
  role-to-assume:
    description: The ARN of the role to assume
    required: true
runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 3600
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Check ECR Repository Exists
      env:
        ECR_REPOSITORY: ${{ github.event.repository.name }}
      shell: bash
      run: |
        aws ecr describe-repositories --repository-names $ECR_REPOSITORY
    - name: Add permissions to repository
      env:
        ECR_REPOSITORY: ${{ github.event.repository.name }}
      shell: bash
      run: |
        aws ecr set-repository-policy --repository-name $ECR_REPOSITORY --policy-text file://standard_policy.json
